site_name: Documentação - Plataforma da Rede de Articulação pela Restauração do Cerrado
site_author: Luiz Pascoal, Renato Gomes Silvério e Tharles de Sousa Andrade

theme:
  name: material

nav:
  - 'HOME': 'index.md'
  - 'Guia do usuário':
    - 'Dados Geográficos': '01-guia_dados_geograficos.md'
    - 'Métricas de Qualidade': '01-guia_metricas_de_qualidade.md'
    - 'Funcionalidades': '01-guia_funcionalidades.md'
    - 'Relatórios': '01-guia_relatorios.md'

  - 'Dados':
    - 'Vetoriais' : '03-dad_vetoriais.md'
    - 'Rasters' : '03-dad_rasters.md'

  - 'Arquitetura de Software':
    - 'Visão geral' : '02-arq_geral.md'
    - 'Servidor de mapas' : '02-arq_servidor_de_mapas.md'
    - 'Servidor de aplicação' : '02-arq_servidor_de_aplicacao.md'
    - 'Deployment da arquitetura do Cerrado DPAT' : '02-arq_execucao_dpat.md'
  
  - 'Métricas de Avaliação' : '04-metricas_de_avaliacao.md'
